import { useState } from 'react';
import { api, solToLamports, lamportsToSol } from '../lib/api';
import QuickBetButtons from './QuickBetButtons';
import { sound } from '../lib/sound';
export default function KenoGame({ userId, balanceLamports, onBalanceChange }) {
  const [picks, setPicks] = useState([]); const [wager, setWager] = useState('0.01'); const [result, setResult] = useState(null); const [loading, setLoading] = useState(false); const [error, setError] = useState(null);
  const boardLocked = loading || Boolean(result);
  function toggle(n) { if (boardLocked) return; setPicks((p) => p.includes(n) ? p.filter((x) => x !== n) : p.length < 10 ? [...p, n] : p); }
  function clearBoard() { if (loading) return; setPicks([]); setResult(null); setError(null); }
  async function play() { if (!userId || !picks.length) return; setLoading(true); setError(null); setResult(null); try { sound.kenoDraw(); const res = await api.playKeno(userId, solToLamports(wager), picks); setTimeout(() => { setResult(res); onBalanceChange(res.newBalanceLamports); res.multiplier > 1 ? sound.bigWin() : res.multiplier === 1 ? sound.smallWin() : sound.lose(); }, 520); } catch (err) { setError(err.message); } finally { setTimeout(() => setLoading(false), 550); } }
  const boost = Math.max(0.35, (11 - picks.length) / 3).toFixed(2);
  return <div className="panel keno-game"><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}><h2 style={{ margin: 0, fontSize: 18 }}>Keno</h2><span className="mono" style={{ fontSize: 12, color: 'var(--text-muted)' }}>Pick up to 10 numbers</span></div><div className="keno-boost">{picks.length ? `${picks.length} pick${picks.length === 1 ? '' : 's'} · ${boost}x multiplier boost` : 'Choose fewer numbers for a higher multiplier'}</div><div className={`keno-grid ${loading ? 'keno-drawing' : ''}`}>{Array.from({ length: 40 }, (_, i) => i + 1).map((n) => <button key={n} disabled={boardLocked} onClick={() => toggle(n)} className={`keno-number ${picks.includes(n) ? 'keno-picked' : ''} ${result?.drawn.includes(n) ? 'keno-drawn' : ''} ${result?.hits.includes(n) ? 'keno-hit' : ''}`}>{n}</button>)}</div>
    {result && <div className={`keno-result ${result.multiplier > 1 ? 'result-win' : 'result-lose'}`}>{result.hits.length} hit{result.hits.length === 1 ? '' : 's'} · {result.multiplier}x {Number(result.payoutLamports) > 0 && `· ${lamportsToSol(result.payoutLamports)} SOL`}</div>}
    <label className="field-label">Wager (SOL)</label><input type="number" min="0" step="0.001" value={wager} onChange={(e) => setWager(e.target.value)} style={{ width: '100%' }} /><div style={{ marginTop: 8 }}><QuickBetButtons wager={wager} setWager={setWager} balanceLamports={balanceLamports} disabled={loading} /></div><div className="keno-actions"><button className="btn" disabled={loading || (!picks.length && !result)} onClick={clearBoard}>Clear board</button><button className="btn btn-brand" disabled={!userId || !picks.length || loading || result} onClick={play}>{loading ? 'Drawing…' : `Draw ${picks.length || ''} number${picks.length === 1 ? '' : 's'}`}</button></div>{error && <p className="mono" style={{ color: 'var(--negative)', fontSize: 13 }}>{error}</p>}</div>;
}
